name: {{name.lowerCase()}}
description: power by emintolgahanpolat
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  collection: ^1.18.0
  connectivity_plus: ^5.0.2
  encrypt: ^5.0.3
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_gen: ^5.4.0
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.4
  image_picker: ^1.0.4
  injectable: ^2.3.2
  intl: ^0.18.1
  json_annotation: ^4.8.1
  package_info_plus: ^5.0.1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.3
  route_map: ^0.0.17
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2

dev_dependencies:
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6
  route_map_generator: ^0.0.17

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/core/res
  assets:
    outputs:
      class_name: AppAssets
  colors:
    outputs:
      class_name: AppColors
    inputs:
      - assets/colors.xml
