name: {{name.lowerCase()}}
description: power by emintolgahanpolat
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  app_settings: ^5.1.1
  cached_network_image: ^3.3.0
  collection: ^1.18.0
  connectivity_plus: ^6.1.0
  flutter_image_compress: ^2.3.0
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_gen: ^5.8.0
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.2
  image_picker: ^1.1.2
  injectable: ^2.3.2
  intl: ^0.19.0
  json_annotation: ^4.8.1
  package_info_plus: ^8.1.1
  pretty_dio_logger: ^1.3.1
  restart_app: ^1.3.2
  retrofit: ^4.4.1
  route_map: ^0.0.17
  shared_preferences: ^2.3.3
  url_launcher: ^6.2.2

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.5
  route_map_generator: ^0.0.17
  flutter_launcher_icons: ^0.14.2
flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/core/res
  assets:
    outputs:
      class_name: AppAssets
  colors:
    outputs:
      class_name: AppColors
    inputs:
      - assets/colors.xml

flutter_launcher_icons:
  image_path: "assets/flavor/logo.png"
  android: true
  background_color_ios: "#0B1A39"
  adaptive_icon_background: "#0B1A39"
  adaptive_icon_foreground: "assets/flavor/logo_fg.png"
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/flavor/logo_fg.png"
