name: {{name.lowerCase()}}
description: power by emintolgahanpolat
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  app_settings: ^6.1.1
  cached_network_image: ^3.3.0
  collection: ^1.19.1
  connectivity_plus: ^6.1.0
  flutter_image_compress: ^2.4.0
  google_fonts: ^6.2.1

  device_info_plus: ^11.5.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_gen: ^5.10.0
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  go_router: ^16.0.0
  image_picker: ^1.1.2
  injectable: ^2.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  package_info_plus: ^8.3.0
  pretty_dio_logger: ^1.4.0

  retrofit: ^4.6.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.5.4
  flutter_gen_runner: ^5.10.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5
  retrofit_generator: ^9.7.0
  flutter_launcher_icons: ^0.14.4
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/core/res
  assets:
    outputs:
      class_name: AppAssets
  colors:
    outputs:
      class_name: AppColors
    inputs:
      - assets/colors.xml

flutter_launcher_icons:
  image_path: "assets/flavor/logo.png"
  android: true
  background_color_ios: "#0B1A39"
  adaptive_icon_background: "#0B1A39"
  adaptive_icon_foreground: "assets/flavor/logo_fg.png"
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/flavor/logo_fg.png"
